apiVersion: v1
kind: Pod
metadata:
  name: debasish
spec:
  containers:
  - image: busybox
    command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
    name: debasish
  restartPolicy: Always