apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: company_globant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company_globant
  template:
    metadata:
      labels:
        app: company_globant
    spec:
      containers:
      - name: front-end
        image: nginx:1.14.2
        ports:
        - containerPort: 80